### ISSUE TITLE
Get attribute and cookies

### ISSUE THREAD

**Issue by tomasserravento** [douglasdcm/caqui#40]
Hi, how are you? First thank you for making this library. I have started using it yesterday and it works perfectly (and really fast).

While learning to use it I have encountered two things I would need (that maybe many people will also need):
1. get_attribute method (which I added in #39 )
2. get_cookies method (the equivalent of what I do with Selenium: driver.get_cookies() )

Do you know how to make number 2 a feature?

Thank you so much for this work!

**Comment by tomasserravento** [comment]
I discovered how to get cookies so I added it in #39 

I have tested it and it works fine! I hope you could merge it and update to pypi.

Thanks for all!

**Comment by tomasserravento** [comment]
Thanks for the merge mate @douglasdcm . Will you be able to push the release to pypi today?

Thank you!

**Comment by douglasdcm** [comment]
Hi, @tomasserravento I'm not receiving notifications in my email.I didn't have saw this issue. The point is already updated with your changes. Thanks a lot again for your help
