### ISSUE TITLE
Question about headless session

### ISSUE THREAD

**Issue by tomasserravento** [douglasdcm/caqui#42]
Hey, @douglasdcm , I have a question that maybe you know the answer.

Im trying to create a session which wont open a google chrome tab in my computer. Do you know how can I make this with caqui?

Actually with Selenium I need to do this:
``
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--headless")  # Agregar argumento para ejecutar en modo headless

driver = webdriver.Chrome(options=options)
``

Thanks a lot!

**Comment by douglasdcm** [comment]
Hi, @tomasserravento I still don't know. I created an issue to investigate it https://github.com/douglasdcm/caqui/issues/1

**Comment by tomasserravento** [comment]
Is there a way I can create a driver with selenium and then use it with caqui? @douglasdcm

**Comment by tomasserravento** [comment]
Hmm I managed to make it headless but it cant find elements now.

In order to make it headless you need to change this in capabilities: capabilities = {"browserName": "chrome", "marionette": True, "acceptInsecureCerts": True, "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--headless"]}}

Problem now is I get this error which I dont get without headless:
`  File "C:\Users\Usuario\Desktop\Prueba Tickets\obtenerLinks.py", line 78, in get_all_links
    anchors = await asynchronous.find_elements(
  File "C:\Users\Usuario\Desktop\Prueba Tickets\venv\lib\site-packages\caqui\asynchronous.py", line 111, in find_elements
    raise WebDriverError(
caqui.exceptions.WebDriverError: Failed to find element by 'xpath'-'//span[@id='idTest']'.`

This works fine without headless in caqui and works fine with headless with selenium @douglasdcm

**Comment by douglasdcm** [comment]
Hi @tomasserravento thanks a lot to find the correct way to set headless. How did you find it? If you have a link for reference I'd like to study it later. I ran it here and it worked fine. I just added the parameters in capabilities dictionary in sample.py. Look this small [video](https://youtu.be/_jBRdJR_HFc)
Can you try to do the same in this file? If you still have issues, let me know, so that we can find the problem together. 

Here is the code
```
        capabilities = {
            "desiredCapabilities": {
                "browserName": "chrome",
                "marionette": True,
                "acceptInsecureCerts": True,
                "pageLoadStrategy": "normal",
                "goog:chromeOptions": {"extensions": [], "args": ["--headless"]},
            }
        }
```

**Comment by tomasserravento** [comment]
Hey @douglasdcm , in order to find it I started to see how Selenium worked and started printing the body they sent on the create session request. Thats how I got it.

Ill try that code you sent me. I have tried this one and got crazy because it wasnt working, after some debugging, with this capabilities Im going to show you, in order to get session you first need to get value:

```
capabilities = {
            "capabilities": {
                "alwaysMatch": {
                    "browserName": "chrome",
                    "pageLoadStrategy": "normal",
                    "goog:chromeOptions": {
                        "extensions": [],
                        "args": ["--headless"]
                    }
                }
            }
        }
```

With that sent to the request, this is the response I got:

```
{'value': {'capabilities': {'acceptInsecureCerts': False, 'browserName': 'chrome', 'browserVersion': '114.0.5735.91', 'chrome': {'chromedriverVersion': '114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})', 'userDataDir': 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\scoped_dir40304_1648383192'}, 'goog:chromeOptions': {'debuggerAddress': 'localhost:53606'}, 'networkConnectionEnabled': False, 'pageLoadStrategy': 'normal', 'platformName': 'windows', 'proxy': {}, 'setWindowRect': True, 'strictFileInteractability': False, 'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000}, 'unhandledPromptBehavior': 'dismiss and notify', 'webauthn:extension:credBlob': True, 'webauthn:extension:largeBlob': True, 'webauthn:extension:minPinLength': True, 'webauthn:extension:prf': True, 'webauthn:virtualAuthenticators': True}, 'sessionId': '3ceda3c5eeabbd04d1d8e8d6e76ef14a'}}
```

So I had to make this change:
```
async def get_session(driver_url, capabilities):
    """Opens a browser and a session. This session is used for all functions to perform events in the page"""
    try:
        payload = json.dumps(capabilities)
        url = f"{driver_url}/session"
        response = await __post(url, payload)
        print("PROBANDOOO", response)
        sessionId = response.get("sessionId")
        if sessionId is None:
            sessionId = response.get("value").get("sessionId")
        return sessionId
    except Exception as error:
        raise WebDriverError("Failed to open session.") from error
```

**Comment by tomasserravento** [comment]
What you said works too! Thanks so much!

**Comment by douglasdcm** [comment]
Great! So, can we close this issue?

**Comment by douglasdcm** [comment]
Closing due inactive
