### ISSUE TITLE
Test using Winium webdriver

### ISSUE THREAD

**Issue by douglasdcm** [douglasdcm/caqui#5]

**Comment by douglasdcm** [comment]
@tomasserravento sorry bother you with this request, but I noted you use Windows OS. This issue and the https://github.com/douglasdcm/caqui/issues/6 are tests related to webdrivers for Windows. It is basically start these webdrivers and run the test suite. For example, winium can be downloaded from here Winium.Desktop.Driver.zip

I didn't tested it yet because I use Linux and didn't finished to setup my Virtualbox with windows

If it works, update the table in Readme file

Fell free to ignore it if you don't have time to test :)

**Comment by tomasserravento** [comment]
Hey mate, Ill try to see if I can setup that (Im not really pro with this stuff haha)..

Also, for your information, Im using Chromedriver v114 and it works fine (so it can be updated in the table)

`(venv) PS C:\Users\Usuario\Desktop\Prueba> ./chromedriver --port=9999
Starting ChromeDriver 114.0.5735.90 (xxxxxx-refs/branch-heads/5735@{#1052}) on port 9999
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.`

**Comment by douglasdcm** [comment]
I'm glad to know it works for chrome 114. I'll update the table.

About the winium, no worries. As far as I remember, it is possible to start it with `./winium --port=9999` like done for chrome, but I used it a long time ago. I need to confirm it. Maybe it has a `-h` parameter

**Comment by douglasdcm** [comment]
Fixed in MR #49 . Readme file updated
