### ISSUE TITLE
Raise exceptions when element not found

### ISSUE THREAD

**Issue by tomasserravento** [douglasdcm/caqui#63]
Hey mate, how are you? I hope you are doing well!

I have this small suggestion: it would be amazing when an element is not found that an exception is being raised (such as Selenium does). It is quite annoying to have to check the returned string.

Im going to push soon swith_to additions!

Thanks for the amazing work!

**Comment by douglasdcm** [comment]
Thank you for the issue. I'll try to fix it as soon as possible

**Comment by douglasdcm** [comment]
Fixed in MR #64

**Comment by tomasserravento** [comment]
Thank you mate @douglasdcm !

I have already developed the switch_to methods, I only need to add the tests! (Ill push them as soon as I have time, Im really busy right now)

**Comment by douglasdcm** [comment]
Hey, thank you! No worries. Push the changes. I can add the tests. :)
