### ISSUE TITLE
Implement switch to an iFrame functionality

### ISSUE THREAD

**Issue by yury-dubinin** [douglasdcm/caqui#76]
Hi @douglasdcm ,

I have been trying to migrate to your library and noticed that functionality to switch to an IFrame is missing.
Some pages just display other pages inside an iFrame and it would be very useful to access it.

Normally one can access an iFrame with the following code:
`iframe = driver.find_elements(By.TAG_NAME, 'iframe')`
`driver.switch_to.frame(iframe[0])`

I am not sure how to tackle this issue, so just wanted to let you know.

**Comment by douglasdcm** [comment]
Hi, @yury-dubinin it is one of the items in my list  https://github.com/douglasdcm/caqui/issues/7
I'll try to implement it soon.

@tomasserravento if you have a draft of it that you can be shared, let us know

**Comment by douglasdcm** [comment]
Add switch to frame in MR #77 
Let me know if it has any issue, please!
